const formTypes = {
  SET_FIRST_NAME: "SET_FIRST_NAME",
  SET_LAST_NAME: "SET_LAST_NAME",
  SET_WORK_PHONE: "SET_WORK_PHONE",
  SET_LANDLINE: "SET,_LANDLINE",
  SET_WORK_EMAIL: "SET_WORK_EMAIL",
  SET_EMAIL: "SET_EMAIL",
  RESET_FORM_STATE: "RESET_FORM_STATE",
};

export default formTypes;
